// sal.h - Microsoft source annotation language: no meaning outside MSVC's /analyze; all empty (web build).
#pragma once
#define _In_
#define _In_opt_
#define _In_z_
#define _In_opt_z_
#define _In_reads_(x)
#define _In_reads_opt_(x)
#define _In_reads_bytes_(x)
#define _In_reads_bytes_opt_(x)
#define _Out_
#define _Out_opt_
#define _Out_writes_(x)
#define _Out_writes_opt_(x)
#define _Out_writes_bytes_(x)
#define _Out_writes_bytes_opt_(x)
#define _Out_writes_z_(x)
#define _Out_writes_to_(x, y)
#define _Inout_
#define _Inout_opt_
#define _Inout_z_
#define _Inout_updates_(x)
#define _Inout_updates_opt_(x)
#define _Inout_updates_bytes_(x)
#define _Outptr_
#define _Outptr_opt_
#define _Outptr_result_maybenull_
#define _Outptr_result_bytebuffer_(x)
#define _COM_Outptr_
#define _COM_Outptr_opt_
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Check_return_
#define _Must_inspect_result_
#define _Success_(x)
#define _Printf_format_string_
#define _Null_terminated_
#define _Field_size_(x)
#define _Field_size_opt_(x)
#define _Field_size_bytes_(x)
#define _Field_size_bytes_opt_(x)
#define _Reserved_
#define _Pre_
#define _Post_
#define _Deref_out_
#define _Frees_ptr_
#define _Frees_ptr_opt_
#define _Use_decl_annotations_
#define _When_(x, y)
#define _Analysis_assume_(x)
#define __in
#define __in_opt
#define __out
#define __out_opt
#define __inout
#define __inout_opt
#define __in_ecount(x)
#define __in_bcount(x)
#define __in_bcount_opt(x)
#define __out_ecount(x)
#define __out_bcount(x)
#define __out_bcount_opt(x)
#define __deref_out
#define __deref_out_opt
#define __reserved
